server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: reporting-service
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "*"
