version: "3.9"

services:
  redpanda:
    image: redpandadata/redpanda:v24.2.5
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1024M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"

  console:
    image: redpandadata/console:latest
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKERS: "redpanda:9092"
    ports:
      - "8080:8080"

  orders-service:
    build:
      context: ../
      dockerfile: services/orders-service/Dockerfile
    depends_on:
      - redpanda
      - jaeger
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: orders-service
    ports:
      - "8081:8081"

  payments-service:
    build:
      context: ../
      dockerfile: services/payments-service/Dockerfile
    depends_on:
      - redpanda
      - jaeger
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: payments-service
    ports:
      - "8083:8083"

  shipping-service:
    build:
      context: ../
      dockerfile: services/shipping-service/Dockerfile
    depends_on:
      - redpanda
      - jaeger
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: shipping-service
    ports:
      - "8084:8084"

  auditor-service:
    build:
      context: ../
      dockerfile: services/auditor-service/Dockerfile
    depends_on:
      - redpanda
      - jaeger
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: auditor-service
    ports:
      - "8085:8085"

  notification-service:
    build:
      context: ../
      dockerfile: services/notification-service/Dockerfile
    depends_on:
      - redpanda
      - jaeger
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: notification-service
    ports:
      - "8086:8086"

  reporting-service:
    build:
      context: ../
      dockerfile: services/reporting-service/Dockerfile
    depends_on:
      - redpanda
      - jaeger
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: reporting-service
    ports:
      - "8088:8088"

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
